INSERT INTO burgers (burger_name) VALUES ('The Fuh-gouda-bout-it Burger');
INSERT INTO burgers (burger_name) VALUES ('Little Chop of Horseradish Burger');
INSERT INTO burgers (burger_name, devoured ) VALUES ('My Bloody Kale-entine Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Absentee Shallot Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Land of the Slaw-st Burger', true);
INSERT INTO burgers (burger_name) VALUES ('Focaccia Red Handed Burger');
INSERT INTO burgers (burger_name) VALUES ('Tank God Its Fried Egg Burger');
INSERT INTO burgers (burger_name) VALUES ('She is a Super Leek Burger');
INSERT INTO burgers (burger_name, devoured ) VALUES ('The Dont Dream Its Okra Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Stop or My Mom Will Shoots Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Two Karat Burger', true);
INSERT INTO burgers (burger_name) VALUES ('Say it Aint Cilantro Burger');
INSERT INTO burgers (burger_name) VALUES ('Pao com ovo');
INSERT INTO burgers (burger_name) VALUES ('Misto Quente');
INSERT INTO burgers (burger_name, devoured ) VALUES ('X-Salada', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('X-Tudo', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('X-Infarto', true);